name: Build Schemata

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  build_schemata:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Build schemata
        run: ant build-customizations
        env:
          ANT_OPTS: "-Dsaxon.feature.ignoreSAXSourceParser=true"

      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a #v7.0.1
        with:
          name: mei-schemata-${{ github.sha }}
          path: dist/schemata
